#ifndef _SYSTEMS_H_
#define _SYSTEMS_H_

#include "stdafx.h"
#include "Macros.h"

#define FOREACH_ARCADE_BOARD(ARCADE_BOARD)  	\
    ARCADE_BOARD(TAITO)   			\
    ARCADE_BOARD(TAITO_2)   			\
    ARCADE_BOARD(NESICA)			\
    ARCADE_BOARD(NONE)

enum CONFIG_ARCADE_BOARD_ENUM {
	FOREACH_ARCADE_BOARD(GENERATE_ENUM)
};

static const char *CONFIG_ARCADE_BOARD_ENUM_STRING[] = {
	FOREACH_ARCADE_BOARD(GENERATE_STRING)
};


#endif
