#ifndef _ENUM_DIRECT_INPUT_H_
#define _ENUM_DIRECT_INPUT_H_

#include "stdafx.h"
#include "macros.h"

#define FOREACH_INPUT_MANAGER(INPUT)   		\
	INPUT(P1_START)		\
	INPUT(P1_COIN)		\
	INPUT(P1_SERVICE)	\
	INPUT(P1_UP)		\
	INPUT(P1_DOWN)		\
	INPUT(P1_LEFT)		\
	INPUT(P1_RIGHT)		\
	INPUT(P1_BUTTON_1)	\
	INPUT(P1_BUTTON_2)	\
	INPUT(P1_BUTTON_3)	\
	INPUT(P1_BUTTON_4)	\
	INPUT(P1_BUTTON_5)	\
	INPUT(P1_BUTTON_6)	\
	INPUT(P2_START)		\
	INPUT(P2_COIN)		\
	INPUT(P2_SERVICE)	\
	INPUT(P2_UP)		\
	INPUT(P2_DOWN)		\
	INPUT(P2_LEFT)		\
	INPUT(P2_RIGHT)		\
	INPUT(P2_BUTTON_1)	\
	INPUT(P2_BUTTON_2)	\
	INPUT(P2_BUTTON_3)	\
	INPUT(P2_BUTTON_4)	\
	INPUT(P2_BUTTON_5)	\
	INPUT(P2_BUTTON_6)	\
	INPUT(TEST_MODE)	\
	INPUT(EXIT_CODE)	\
	INPUT(TEST_TILT1)	\
	INPUT(TEST_TILT2)	\
	INPUT(TEST_TILT3)	\
	INPUT(_SIZE_)	

enum CONFIG_INPUT_ENUM {
	FOREACH_INPUT_MANAGER(GENERATE_ENUM)
};

static const char *CONFIG_INPUT_ENUM_STRING[] = {
	FOREACH_INPUT_MANAGER(GENERATE_STRING)
};

#endif