#ifndef _READ_RESOLUTION_DISPLAY_H_
#define _READ_RESOLUTION_DISPLAY_H_

#include "stdafx.h"
#include "macros.h"

#define FOREACH_RESOLUTION(RESOLUTION)   		\
	RESOLUTION(FULLSCREEN_NATIVE)			\
	RESOLUTION(FULLSCREEN_NATIVE_ROTATION_90)	\
	RESOLUTION(FULLSCREEN_NATIVE_ROTATION_180)	\
	RESOLUTION(FULLSCREEN_NATIVE_ROTATION_270)	\
	RESOLUTION(FULLSCREEN)				\
	RESOLUTION(FULLSCREEN_ROTATION_90)		\
	RESOLUTION(FULLSCREEN_ROTATION_180)		\
	RESOLUTION(FULLSCREEN_ROTATION_270)		\
	RESOLUTION(WINDOWED)				\
	RESOLUTION(WINDOWED_ROTATION_90)		\
	RESOLUTION(WINDOWED_ROTATION_180)		\
	RESOLUTION(WINDOWED_ROTATION_270)		\
	RESOLUTION(WINDOWED_CENTER)			\
	RESOLUTION(WINDOWED_CENTER_ROTATION_90)		\
	RESOLUTION(WINDOWED_CENTER_ROTATION_180)	\
	RESOLUTION(WINDOWED_CENTER_ROTATION_270)	\
	RESOLUTION(FULLSCREEN_1_1  )			\
	RESOLUTION(FULLSCREEN_2_1  )			\
	RESOLUTION(FULLSCREEN_3_2  )			\
	RESOLUTION(FULLSCREEN_3_4  )			\
	RESOLUTION(FULLSCREEN_4_1  )			\
	RESOLUTION(FULLSCREEN_4_3  )			\
	RESOLUTION(FULLSCREEN_5_3  )			\
	RESOLUTION(FULLSCREEN_5_4  )			\
	RESOLUTION(FULLSCREEN_6_5  )			\
	RESOLUTION(FULLSCREEN_7_9  )			\
	RESOLUTION(FULLSCREEN_8_3  )			\
	RESOLUTION(FULLSCREEN_8_7  )			\
	RESOLUTION(FULLSCREEN_9_16 )			\
	RESOLUTION(FULLSCREEN_16_9 )			\
	RESOLUTION(FULLSCREEN_16_10)			\
	RESOLUTION(FULLSCREEN_16_15)			\
	RESOLUTION(FULLSCREEN_19_12)			\
	RESOLUTION(FULLSCREEN_19_14)			\
	RESOLUTION(FULLSCREEN_30_17)			\
	RESOLUTION(FULLSCREEN_32_9 )	

enum CONFIG_RESOLUTION_ENUM {
	FOREACH_RESOLUTION(GENERATE_ENUM)
};

static const char *CONFIG_RESOLUTION_ENUM_STRING[] = {
	FOREACH_RESOLUTION(GENERATE_STRING)
};

using namespace std;

class ResolutionDisplay
{
public:

	ResolutionDisplay();
	~ResolutionDisplay();
	const char* toString(CONFIG_RESOLUTION_ENUM i);
	CONFIG_RESOLUTION_ENUM toEnum(string i);


private:

	map<std::string, CONFIG_RESOLUTION_ENUM>  mapStringEnum = {
	   { CONFIG_RESOLUTION_ENUM_STRING[0], FULLSCREEN_NATIVE},
	   { CONFIG_RESOLUTION_ENUM_STRING[2], FULLSCREEN_NATIVE_ROTATION_90},
	   { CONFIG_RESOLUTION_ENUM_STRING[3], FULLSCREEN_NATIVE_ROTATION_180},
	   { CONFIG_RESOLUTION_ENUM_STRING[4], FULLSCREEN_NATIVE_ROTATION_270},
	   { CONFIG_RESOLUTION_ENUM_STRING[1], FULLSCREEN },
	   { CONFIG_RESOLUTION_ENUM_STRING[2], FULLSCREEN_ROTATION_90},
	   { CONFIG_RESOLUTION_ENUM_STRING[3], FULLSCREEN_ROTATION_180},
	   { CONFIG_RESOLUTION_ENUM_STRING[4], FULLSCREEN_ROTATION_270},
	   { CONFIG_RESOLUTION_ENUM_STRING[5], WINDOWED},
	   { CONFIG_RESOLUTION_ENUM_STRING[6], WINDOWED_ROTATION_90},
	   { CONFIG_RESOLUTION_ENUM_STRING[7], WINDOWED_ROTATION_180},
	   { CONFIG_RESOLUTION_ENUM_STRING[8], WINDOWED_ROTATION_270},
	   { CONFIG_RESOLUTION_ENUM_STRING[9],WINDOWED_CENTER},
	   { CONFIG_RESOLUTION_ENUM_STRING[10], WINDOWED_CENTER_ROTATION_90},
	   { CONFIG_RESOLUTION_ENUM_STRING[11], WINDOWED_CENTER_ROTATION_180},
	   { CONFIG_RESOLUTION_ENUM_STRING[12], WINDOWED_CENTER_ROTATION_270 },
	   { CONFIG_RESOLUTION_ENUM_STRING[16], FULLSCREEN_1_1  },
	   { CONFIG_RESOLUTION_ENUM_STRING[17], FULLSCREEN_2_1  },
	   { CONFIG_RESOLUTION_ENUM_STRING[18], FULLSCREEN_3_2  },
	   { CONFIG_RESOLUTION_ENUM_STRING[19], FULLSCREEN_3_4  },
	   { CONFIG_RESOLUTION_ENUM_STRING[20], FULLSCREEN_4_1  },
	   { CONFIG_RESOLUTION_ENUM_STRING[21], FULLSCREEN_4_3  },
	   { CONFIG_RESOLUTION_ENUM_STRING[22], FULLSCREEN_5_3  },
	   { CONFIG_RESOLUTION_ENUM_STRING[23], FULLSCREEN_5_4  },
	   { CONFIG_RESOLUTION_ENUM_STRING[24], FULLSCREEN_6_5  },
	   { CONFIG_RESOLUTION_ENUM_STRING[25], FULLSCREEN_7_9  },
	   { CONFIG_RESOLUTION_ENUM_STRING[26], FULLSCREEN_8_3  },
	   { CONFIG_RESOLUTION_ENUM_STRING[27], FULLSCREEN_8_7  },
	   { CONFIG_RESOLUTION_ENUM_STRING[28], FULLSCREEN_9_16 },
	   { CONFIG_RESOLUTION_ENUM_STRING[29], FULLSCREEN_16_9 },
	   { CONFIG_RESOLUTION_ENUM_STRING[30], FULLSCREEN_16_10},
	   { CONFIG_RESOLUTION_ENUM_STRING[31], FULLSCREEN_16_15},
	   { CONFIG_RESOLUTION_ENUM_STRING[32], FULLSCREEN_19_12},
	   { CONFIG_RESOLUTION_ENUM_STRING[33], FULLSCREEN_19_14},
	   { CONFIG_RESOLUTION_ENUM_STRING[34], FULLSCREEN_30_17},
	   { CONFIG_RESOLUTION_ENUM_STRING[35], FULLSCREEN_32_9 }
	};
	
};


#endif
